pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                sh "mvn -f ${env.GIT_URL}/SpringBootDemo/pom.xml clean -DskipTests package"
            }
        }
        stage("test"){
            steps{
                sh "mvn test"
            }
        }
    }
}
